### PR TITLE
refactor: better resource cleanup handling

### PR DESCRIPTION
**Pull request by eddycharly**
This PR improves resource cleanup handling

### CODE REVIEW

**Review by realshuting — APPROVED** [review]
👍

**Comment by eddycharly** [comment]
I don't understand why deleting a namespace takes more than 2 minutes.

**Comment by realshuting** [comment]
> I don't understand why deleting a namespace takes more than 2 minutes.

Is this because the Kyverno policy selects all operations including DELETE?

**Comment by eddycharly** [comment]
> Is this because the Kyverno policy selects all operations including DELETE?

I don't think so, pods enter the terminating state but it takes more than 2 minutes to get them deleted.

```
kuttl-test-decent-pangolin    hello                                        0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello                                        0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello                                        0/1     ContainerCreating   0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     ContainerCreating   0          0s
kuttl-test-decent-pangolin    hello                                        0/1     Terminating         0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          2s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          3s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          3s
kuttl-test-decent-pangolin    hello                                        1/1     Terminating         0          3s
kuttl-test-decent-pangolin    hello                                        0/1     Terminating         0          4s
kuttl-test-decent-pangolin    hello                                        0/1     Terminating         0          4s
kuttl-test-decent-pangolin    hello                                        0/1     Terminating         0          4s
kuttl-test-decent-pangolin    hello                                        0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello                                        0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello                                        0/1     ContainerCreating   0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     Pending             0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     ContainerCreating   0          0s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          0s
kuttl-test-decent-pangolin    hello                                        0/1     Terminating         0          0s
kuttl-test-decent-pangolin    hello                                        0/1     Terminating         0          2m4s
kuttl-test-decent-pangolin    hello                                        0/1     Terminating         0          2m4s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          2m4s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          2m4s
kuttl-test-decent-pangolin    hello2                                       0/1     Terminating         0          2m4s
```

**Comment by chipzoller** [comment]
> I don't understand why deleting a namespac

Are you forcing the deletion? Because, if not, we probably should be.

**Comment by eddycharly** [comment]
> > I don't understand why deleting a namespac
> 
> Are you forcing the deletion? Because, if not, we probably should be.

I'm not, why should we force the deletion ?
There's something wrong with lifecycle management, i need to fix that.
It looks like there's some exponential backoff going on too:
```
E1128 15:52:56.556441       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:56.622689       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:56.697307       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:56.779335       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:56.881019       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:57.019074       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:57.237376       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:57.631233       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:58.337876       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:52:59.696471       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:53:02.344102       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:53:07.527493       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:53:17.864083       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
E1128 15:53:38.425059       1 namespace_controller.go:162] deletion of namespace kuttl-test-decent-pangolin failed: unexpected items still remain in namespace: kuttl-test-decent-pangolin for gvr: /v1, Resource=pods
I1128 15:54:24.465164       1 namespace_controller.go:185] Namespace has been deleted kuttl-test-decent-pangolin
```

**Comment by chipzoller** [comment]
>I'm not, why should we force the deletion ?

Why do we care about graceful deletion? We're tearing everything down to run the next test.

**Comment by eddycharly** [comment]
> Why do we care about graceful deletion?

To make sure deletion works as expected. Cleanup is important and raising an error when deletion fails makes sense to me.

**Comment by chipzoller** [comment]
Again though, why do we care? Are there situations where we need to know this?

**Comment by eddycharly** [comment]
Finally, fixed !

**Pull request merged**
