### PR TITLE
feat: add UPDATE support

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds UPDATE support.

### CODE REVIEW

**Comment by chipzoller** [comment]
Don't understand what this PR does. Please explain more thoroughly.

**Comment by eddycharly** [comment]
When an object already exists, kuttl will issue a `Patch` to update the existing object.
Sometimes you want to issue an `Update` though (replacing the old object) like when you want to cleat annotations.

**Comment by eddycharly** [comment]
This [test](https://github.com/kyverno/kyverno/tree/main/test/conformance/kuttl/validate/e2e/yaml-signing) won't pass if we update the deployment using a `Patch` (annotations on the old deployment will be preserved)

**Comment by chipzoller** [comment]
Swap the good and bad steps. Bad fails first therefore nothing to replace.

**Comment by eddycharly** [comment]
It is useful, why the hell are we ALWAYS issuing a `PATCH` ?

**Comment by eddycharly** [comment]
We need some control on this.

**Comment by chipzoller** [comment]
@realshuting can you help review?

**Pull request closed without merging**
