### PR TITLE
chore: list namespaces at the end of tests

### PR DESCRIPTION
**Pull request by eddycharly**
This PR lists namespaces at the end of tests to help troubleshooting dangling namespaces.

### CODE REVIEW

**Comment by chipzoller** [comment]
What's an example output after this change?

**Comment by eddycharly** [comment]
@chipzoller the ci just doesn’t work, I’m going to switch to kind.
Deploying etcd and api server is just not enough 🤷

**Comment by chipzoller** [comment]
We need to kill this file also? https://github.com/kyverno/kuttl/blob/main/kuttl-test.yaml

**Comment by eddycharly** [comment]
I have set `startControlPlane: false`.
Now tests use resources that have been removed in 1.22... oh man :(

**Comment by chipzoller** [comment]
The `create-or-update` test case needs its CRD updated to v1.

**Comment by eddycharly** [comment]
> The create-or-update test case needs its CRD updated to v1.

Was not updated already ?

**Comment by chipzoller** [comment]
No, it was v1beta1.

**Comment by eddycharly** [comment]
Where are you seeing this ??

**Comment by chipzoller** [comment]
Creating of this CRD fails in K8s 1.24 because v1beta1 is no longer served: https://github.com/kyverno/kuttl/blob/main/pkg/test/test_data/create-or-update/00-crd.yaml

**Comment by eddycharly** [comment]
I mean in the source.
Anyway, I'm bored, going to switch to 1.22...

**Comment by chipzoller** [comment]
Accept the incoming merge from that CRD.

**Comment by eddycharly** [comment]
Most tests are completely bound to testenv :(
I will need to rewrite them to work with kind, for now i'm commenting them out in #8

**Comment by eddycharly** [comment]
Closing, useless

**Pull request closed without merging**
